environments:
  - Staging
  - Production

settings:
  class_name: "AppConfig"

natrium_variables:
  DebugString: "debugString"

plists:
  "PropertyList.plist":
    some_array:
      - "applinks:#{DebugString}"

  "NatriumExampleManualProject/Info.plist":
    CFBundleDisplayName:
      Staging: App_staging
      Production: App

xcconfig:
    PRODUCT_BUNDLE_IDENTIFIER:
        Staging: com.esites.app.staging
        Production:
            Debug: com.esites.app.production
            Release: com.esites.app

variables: !include .natrium-variables.yml

files:
  Files/file.html:
    Staging: Files/file-staging.html
    Production: Files/file-production.html

appicon:
    original: icon.png
    appiconset: NatriumExampleManualProject/Assets.xcassets/AppIcon.appiconset/
    idioms:
      - iphone
      - ipad
    ribbon:
        Production:
          Debug: "PRODUCTION"
          Release: ""
        Staging: "STAGING"

target_specific:
  NatriumExampleManualProject: !include .natrium-target-specific.yml
    

# launch_screen_versioning:
#     path: NatriumExampleManualProject/Base.lproj/LaunchScreen.storyboard
#     labelName: LaunchScreenVersionLabel
#     enabled: true
